#!/bin/bash

cd /var/www/html/easyinfra/snapshots/AshokNagar/ && sh ./takeIt.sh &
cd /var/www/html/easyinfra/snapshots/Banashankari/ && sh ./takeIt.sh &
cd /var/www/html/easyinfra/snapshots/Banaswadi/ && sh ./takeIt.sh &
cd /var/www/html/easyinfra/snapshots/BannerghattaRoad/ && sh ./takeIt.sh &
cd /var/www/html/easyinfra/snapshots/Basaveshwaranagar/ && sh ./takeIt.sh &
cd /var/www/html/easyinfra/snapshots/BelRoad/ && sh ./takeIt.sh &
cd /var/www/html/easyinfra/snapshots/Bellandur/ && sh ./takeIt.sh &
cd /var/www/html/easyinfra/snapshots/BenniganaHalli/ && sh ./takeIt.sh &
cd /var/www/html/easyinfra/snapshots/Bidadi/ && sh ./takeIt.sh &
cd /var/www/html/easyinfra/snapshots/Bommanahalli/ && sh ./takeIt.sh &
cd /var/www/html/easyinfra/snapshots/BrigadeRoad/ && sh ./takeIt.sh &
cd /var/www/html/easyinfra/snapshots/Brookefield/ && sh ./takeIt.sh &
cd /var/www/html/easyinfra/snapshots/BTMLayout/ && sh ./takeIt.sh &
cd /var/www/html/easyinfra/snapshots/Byatarayanapura/ && sh ./takeIt.sh &
cd /var/www/html/easyinfra/snapshots/C.V.RamanNagar/ && sh ./takeIt.sh &
cd /var/www/html/easyinfra/snapshots/Chamarajpet/ && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Dasarahalli/ && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Devanahalli/ && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/DickensonRoad/ && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Doddakallasandra/ && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/DomlurLayout/ && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/DooravaniNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/ElectronicsCity && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/FrazerTown && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/GandhiNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/GangaNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Gavipuram && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Hanumanthanagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Hebbal && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Hennur && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Hesaraghatta && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/HosurRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/HRBRLayout && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/HSRLayout && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/IndiraNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/ITPLRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/JPNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Jalahalli && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/JayaNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/JayachamarajaRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/JayamahalRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/JeevanBheemaNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Kadugodi && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Kadugondanahalli && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Kalasipalyam && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/KalyanNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Kammanahalli && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/KasturbaRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/KasturiNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Kathriguppe && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/KempeGowdaRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Kengeri && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Kodihalli && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Konanakunte && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Koramangala && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/KrishnarajaPuram && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/KumaraswamyLayout && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/LangfordTown && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Lingarajapuram && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Madivala && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/MagrathRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Mahadevapura && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Mahalakshmipuram && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/MahatmaGandhiRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Malleshwaram && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Marathahalli && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/MaruthiNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Mathikere && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/MissionRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/MuseumRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/MysoreRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Nagarathpet && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Nagarbhavi && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Nagasandra && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/NagashettyHalli && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Nagavara && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/NandhiniLayout && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/OTCRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/OldAirportRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Padmanabhanagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Palya && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Peenya && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/RajBhavanRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/RajaRajeshwariNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/RajaRamMohanRoyRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/RamamurthyNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/ResidencyRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/SadashivaNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/SahakaraNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/SampangiramNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/SanjayNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/SankeyRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/SarjapurRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Seshadripuram && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/ShantiNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/StMarksRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/StThomasTown && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Subramanyapura && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Thippasandra && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/TumkurRoad && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Ulsoor && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Uttarahalli && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Vaiyyalikaval && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Varthur && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Vidyaranyapura && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/VijayNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Vimanapura && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/VivekNagar && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/VVPuram && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Whitefield && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/WilsonGarden && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Yelahanka && sh ./takeIt.sh & 
cd /var/www/html/easyinfra/snapshots/Yeshwanthpur && sh ./takeIt.sh

wait
